name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  
jobs:
  check-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      - name: Verify pylint installation
        run: |
          echo "Verifying pylint installation..."
          pylint --version

      - name: Run pylint
        run: |
          echo "Running pylint..."
          if git ls-files '*.py' | grep -q .; then
            pylint $(git ls-files '*.py')
          else
            echo "No Python files to lint."
          fi
